package miniencuesta;

/**
 *
 * @author gustavo
 */
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.ArrayList;

public class VistaEncuesta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEncuesta.class.getName());
    private ButtonGroup bgSistemaOperativo;
    
    public VistaEncuesta() {
    initComponents();
    agruparRadioButtons();
    
    //texto inicial de la etiqueta
    lblValorSlider.setText(String.valueOf(sliderHoras.getValue()));
    
    //se activa cada vez que el slider cambia
    sliderHoras.addChangeListener(new javax.swing.event.ChangeListener() {
        
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            
            int valorActual = sliderHoras.getValue();
            
            lblValorSlider.setText(String.valueOf(valorActual));
        }
    });
}
    
    private void agruparRadioButtons(){
        bgSistemaOperativo = new ButtonGroup();
        bgSistemaOperativo.add(rbWindows);
        bgSistemaOperativo.add(rbLinux);
        bgSistemaOperativo.add(rbMac);
    }
    
    public String getSistemaOperativoSeleccionado(){
        if (rbWindows.isSelected())return "Windows";
        if (rbLinux.isSelected())return "Linux";
        if (rbMac.isSelected())return "Mac";
        return null; //si no ha seleccionado nada
    }
    
    public List<String> getEspecialidadesSeleccionadas(){
    List<String> seleccionadas = new ArrayList<>();
    if (chkProgramacion.isSelected()) {
        seleccionadas.add("Programacion");
    }
    if (chkDiseno.isSelected()) {
        seleccionadas.add("Diseno Grafico");
    }
    if (chkAdministracion.isSelected()) {
        seleccionadas.add("Administracion");
    }
    return seleccionadas;
    }
    
    public int getHorasSeleccionadas(){
        return sliderHoras.getValue();
    }
    
    public void addGenerarListener(ActionListener listener){
        btnGenerar.addActionListener(listener);
    }
    public void limpiarCampos(){
    bgSistemaOperativo.clearSelection();
    sliderHoras.setValue(0);

    // Desmarca cada checkbox
    chkProgramacion.setSelected(false);
    chkDiseno.setSelected(false);
    chkAdministracion.setSelected(false);
    }

    public JButton getBtnGenerar() {
        return btnGenerar;
    }

    public JButton getBtnVerEstadisticas() {
        return btnVerEstadisticas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbWindows = new javax.swing.JRadioButton();
        rbLinux = new javax.swing.JRadioButton();
        rbMac = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sliderHoras = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        lblValorSlider = new javax.swing.JLabel();
        btnVerEstadisticas = new javax.swing.JButton();
        chkProgramacion = new javax.swing.JCheckBox();
        chkDiseno = new javax.swing.JCheckBox();
        chkAdministracion = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Encuesta");
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        rbWindows.setText("Windows");
        rbWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWindowsActionPerformed(evt);
            }
        });

        rbLinux.setText("Linux");

        rbMac.setText("Mac");

        sliderHoras.setMaximum(10);
        sliderHoras.setMinorTickSpacing(1);
        sliderHoras.setPaintTicks(true);
        sliderHoras.setValue(0);

        jLabel1.setText("Elije un Sistema Operativo");

        jLabel2.setText("Elije tu especialidad");

        jLabel3.setText("Horas dedicadas en el ordenador");

        btnGenerar.setText("Generar");

        lblValorSlider.setText("5");

        btnVerEstadisticas.setText("Ver estadisticas");
        btnVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadisticasActionPerformed(evt);
            }
        });

        chkProgramacion.setText("Programación");
        chkProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramacionActionPerformed(evt);
            }
        });

        chkDiseno.setText("Diseño Gráfico");

        chkAdministracion.setText("Administración");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblValorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbMac)
                    .addComponent(rbLinux)
                    .addComponent(rbWindows)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkProgramacion)
                    .addComponent(chkDiseno)
                    .addComponent(chkAdministracion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGenerar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerEstadisticas))
                        .addComponent(sliderHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbWindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbLinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMac)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(chkProgramacion)
                .addGap(18, 18, 18)
                .addComponent(chkDiseno)
                .addGap(18, 18, 18)
                .addComponent(chkAdministracion)
                .addGap(22, 22, 22)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblValorSlider)
                .addGap(18, 18, 18)
                .addComponent(sliderHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnVerEstadisticas))
                .addGap(143, 143, 143))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWindowsActionPerformed

    private void btnVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEstadisticasActionPerformed

    private void chkProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaEncuesta().setVisible(true));
    }
    public void addVerEstadisticasListener(ActionListener listener) {
    btnVerEstadisticas.addActionListener(listener);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.JCheckBox chkAdministracion;
    private javax.swing.JCheckBox chkDiseno;
    private javax.swing.JCheckBox chkProgramacion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblValorSlider;
    private javax.swing.JRadioButton rbLinux;
    private javax.swing.JRadioButton rbMac;
    private javax.swing.JRadioButton rbWindows;
    private javax.swing.JSlider sliderHoras;
    // End of variables declaration//GEN-END:variables
}
