package miniencuesta;

/**
 *
 * @author gustavo
 */
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import java.awt.event.ActionListener;

public class VistaEncuesta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEncuesta.class.getName());
    private ButtonGroup bgSistemaOperativo;
    private ButtonGroup bgEspecialidad;
    
    public VistaEncuesta() {
    initComponents();
    agruparRadioButtons();
    
    //texto inicial de la etiqueta
    lblValorSlider.setText(String.valueOf(sliderHoras.getValue()));
    
    //se activa cada vez que el slider cambia
    sliderHoras.addChangeListener(new javax.swing.event.ChangeListener() {
        
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            
            int valorActual = sliderHoras.getValue();
            
            lblValorSlider.setText(String.valueOf(valorActual));
        }
    });
}
    
    private void agruparRadioButtons(){
        bgSistemaOperativo = new ButtonGroup();
        bgSistemaOperativo.add(rbWindows);
        bgSistemaOperativo.add(rbLinux);
        bgSistemaOperativo.add(rbMac);
        
        bgEspecialidad = new ButtonGroup();
        bgEspecialidad.add (rbProgramacion);
        bgEspecialidad.add (rbDiseno);
        bgEspecialidad.add (rbAdministracion);
    }
    
    public String getSistemaOperativoSeleccionado(){
        if (rbWindows.isSelected())return "Windows";
        if (rbLinux.isSelected())return "Linux";
        if (rbMac.isSelected())return "Mac";
        return null; //si no ha seleccionado nada
    }
    public String getEspecialidadSeleccionada(){
        if(rbProgramacion.isSelected())return "Programacion";
        if(rbDiseno.isSelected())return "Diseno Grafico";
        if(rbAdministracion.isSelected())return "Administracion";
        return null; // si no ha selecionado nada
    }
    
    public int getHorasSeleccionadas(){
        return sliderHoras.getValue();
    }
    
    public void addGenerarListener(ActionListener listener){
        btnGenerar.addActionListener(listener);
    }
    public void limpiarCampos(){
        bgSistemaOperativo.clearSelection();
        bgEspecialidad.clearSelection();
        sliderHoras.setValue(0);
    }

    public JButton getBtnGenerar() {
        return btnGenerar;
    }

    public JButton getBtnVerEstadisticas() {
        return btnVerEstadisticas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbWindows = new javax.swing.JRadioButton();
        rbLinux = new javax.swing.JRadioButton();
        rbMac = new javax.swing.JRadioButton();
        rbProgramacion = new javax.swing.JRadioButton();
        rbDiseno = new javax.swing.JRadioButton();
        rbAdministracion = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sliderHoras = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        lblValorSlider = new javax.swing.JLabel();
        btnVerEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        rbWindows.setText("Windows");
        rbWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWindowsActionPerformed(evt);
            }
        });

        rbLinux.setText("Linux");

        rbMac.setText("Mac");

        rbProgramacion.setText("Programación");
        rbProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProgramacionActionPerformed(evt);
            }
        });

        rbDiseno.setText("Diseño Grafico");

        rbAdministracion.setText("Administracion");

        sliderHoras.setMaximum(10);
        sliderHoras.setMinorTickSpacing(1);
        sliderHoras.setPaintTicks(true);
        sliderHoras.setValue(0);

        jLabel1.setText("Elije un Sistema Operativo");

        jLabel2.setText("Elije tu especialidad");

        jLabel3.setText("Horas dedicadas en el ordenador");

        btnGenerar.setText("Generar");

        lblValorSlider.setText("5");

        btnVerEstadisticas.setText("Ver estadisticas");
        btnVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAdministracion)
                                    .addComponent(rbDiseno)
                                    .addComponent(rbProgramacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbMac)
                            .addComponent(rbLinux)
                            .addComponent(rbWindows)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblValorSlider)
                        .addGap(18, 18, 18)
                        .addComponent(sliderHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnGenerar)
                        .addGap(42, 42, 42)
                        .addComponent(btnVerEstadisticas)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbWindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbLinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMac)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(rbProgramacion)
                .addGap(18, 18, 18)
                .addComponent(rbDiseno)
                .addGap(18, 18, 18)
                .addComponent(rbAdministracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorSlider))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnVerEstadisticas))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWindowsActionPerformed

    private void rbProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbProgramacionActionPerformed

    private void btnVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaEncuesta().setVisible(true));
    }
    public void addVerEstadisticasListener(ActionListener listener) {
    btnVerEstadisticas.addActionListener(listener);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblValorSlider;
    private javax.swing.JRadioButton rbAdministracion;
    private javax.swing.JRadioButton rbDiseno;
    private javax.swing.JRadioButton rbLinux;
    private javax.swing.JRadioButton rbMac;
    private javax.swing.JRadioButton rbProgramacion;
    private javax.swing.JRadioButton rbWindows;
    private javax.swing.JSlider sliderHoras;
    // End of variables declaration//GEN-END:variables
}
